name = energy_drinks
title = Energy Drinks
description = New drinks to drink
optional_depends = default, dye, bucket, farming, x_farming, sugar, mcl_core, mcl_dyes, mcl_dye, mcl_buckets, basic_materials
supported_games = *, mineclone2, minetest_game, mineclonia
author = Sheriff-Unit-3
min_minetest_version = 5.10
