on: [push, pull_request]
jobs:
  luacheck:
    runs-on: codeberg-tiny-lazy
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    steps:
       - name: checkout
         uses: https://code.forgejo.org/actions/checkout@v4
       - name: install and run luacheck
         run: |
           sudo apt-get update && sudo apt-get install -y luarocks
           luarocks install luacheck
           export PATH="$PATH:$(luarocks config user_bin)"
           luacheck .